services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: hurz
      POSTGRES_PASSWORD: hihixd
      POSTGRES_DB: rpg_db
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U hurz -d rpg_db" ]
      interval: 3s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "1337:1337"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge